[package]
name = "k3ymb3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
libc = "0.2.119"
getopts = "0.2.21"
env_logger = "0.9.0"
log = "0.4.14"
sudo = "0.6.0"